
package com.github.lindenb.semontology;
/**
 * Terms from https://github.com/lindenb/semontology
 * A java enum that can be used in your java projects.
 *
 * @author Pierre Lindenbaum PhD @yokofakun
 */
@javax.annotation.Generated(value="xslt",date="2017-04-06T00:14:10+02:00")
public enum Term
{
comment("ID:0000000"),
	I_have_written_it("ID:0000001"),
	please_do_not_look_at_the_code("ID:0000002"),
	I_use_it_regularly("ID:0000003"),
	I_do_not_remember_why_I_wrote_it("ID:0000004"),
	unmaintained("ID:0000005"),
	pull_requests_welcomed("ID:0000006"),
	I_do_not_accept_pull_requests("ID:0000007"),
	it_was_a_one_shot("ID:0000008"),
	I_do_not_understand_how_it_could_work("ID:0000009"),
	I_should_write_some_tests("ID:0000010"),
	I_do_not_understand_my_code("ID:0000011"),
	it_is_deprecated("ID:0000012"),
	better_softwares_exist("ID:0000013"),
	I_would_not_write_it_like_that_now("ID:0000014"),
	I_wrote_it_for_biostars("ID:0000015"),
	I_have_to_used_it_for_years("ID:0000016"),
	just_a_proof_of_concept("ID:0000017"),
	still_in_beta("ID:0000018"),
	autogenerated("ID:0000019"),
	published("ID:0000020"),
	unpublished("ID:0000021"),
	I_should_write_a_paper("ID:0000022"),
	it_is_broken("ID:0000023"),
	documention_is_missing("ID:0000024"),
	documention_exists("ID:0000025"),
	the_code_is_the_documentation("ID:0000026"),
	documentation_is_embbeded("ID:0000027");
private final String acn;
Term(final String acn) { this.acn=acn;}

public String getAccession() { return this.acn;}
public static Term findByAccession(final String acn)
	{
	for(final Term t: Term.values()) {
		if( t.getAccession().equals(acn) ) return t;
		}
	return null;
	}
	
public static void main(final String args[])
	{
	for(final Term t: Term.values()) System.out.println(t.name()+"\t"+t.getAccession());
	}
}

